#=====================================================
# VISUALISATION
#=====================================================

#/vis/disable
/vis/enable
/control/execute ../Visualisation/visu.mac

#=====================================================
# VERBOSITY
#=====================================================

/control/execute ../Verbose/verbose.mac

#=====================================================
# MATERIALS
#=====================================================

/gate/geometry/setMaterialDatabase GateMaterials.db

#=====================================================
# GEOMETRY
#=====================================================

/control/execute ../Geometry/Modular_JPET.mac
/gate/plastic/attachCrystalSD

#=====================================================
# PHANTOM
#=====================================================

/control/execute ../Phantom/pmma_400mm_center.mac
/gate/phantom/attachPhantomSD

#=====================================================
# PHYSICS
#=====================================================

/control/execute ../Physics/protonRT_our.mac

#=====================================================
# ACTORS
#=====================================================

# Statistics for the phantom
#/control/execute ../Actors/phantom_statistics.mac

# Dose actor for the phantom
#/control/execute ../Actors/phantom_dose.mac

#Secondary particles production actor
#/control/execute ../Actors/phantom_secondary.mac

#JPET actors
#/control/execute ../Actors/phantom_jpet_gamma.mac
#/control/execute ../Actors/phantom_jpet_neutron.mac
#/control/execute ../Actors/phantom_jpet_proton.mac
#/control/execute ../Actors/phantom_jpet_genericion.mac
#/control/execute ../Actors/phantom_jpet_positron.mac
#/control/execute ../Actors/phantom_jpet.mac

#JPET global actor

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

/gate/physics/print output/physics.txt

#=====================================================
# SOURCE
#=====================================================

/control/execute ../Sources/proton_beam_test.mac

#=====================================================
# OUTPUT
#=====================================================

/control/execute ../Outputs/Output_scanner.mac

#=====================================================
# RANDOM
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456789
#/gate/random/setEngineSeed auto
#/gate/random/verbose 1

#=====================================================
# ACQUISITION SETTINGS   
#=====================================================

/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/startDAQ
