# POINT SOURCE

/gate/source/addSource twogamma
/gate/source/twogamma/setActivity 1 MBq
/gate/source/twogamma/setType backtoback

/gate/source/twogamma/gps/type Point
/gate/source/twogamma/gps/centre 0. 0. 0. mm
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 511 keV
/gate/source/twogamma/gps/angtype iso

/gate/source/twogamma/visualize 2000 magenta 5

