#=====================================
# Electromagnetic processes
#=====================================

/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel StandardModel

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation e+
/gate/physics/addProcess ElectronIonisation e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.2 0.1 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.2 0.1 mm

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-

/gate/physics/addProcess PositronAnnihilation
/gate/physics/processes/G4PositronAnnihilation/setModel StandardModel

/gate/physics/addProcess eMultipleScattering e-
/gate/physics/addProcess eMultipleScattering e+

/gate/physics/addProcess HadronIonisation
/gate/physics/removeProcess HadronIonisation deuteron
/gate/physics/removeProcess HadronIonisation triton
/gate/physics/removeProcess HadronIonisation He3
/gate/physics/removeProcess HadronIonisation alpha
/gate/physics/removeProcess HadronIonisation GenericIon
/gate/physics/processes/HadronIonisation/setStepFunction proton 0.2 0.05 mm
/gate/physics/processes/HadronIonisation/setStepFunction pi+ 0.2 0.05 mm
/gate/physics/processes/HadronIonisation/setStepFunction pi- 0.2 0.05 mm

/gate/physics/addProcess IonIonisation
/gate/physics/processes/IonIonisation/setStepFunction GenericIon 0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction alpha 0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction deuteron 0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction triton 0.1 0.02 mm
/gate/physics/processes/IonIonisation/setStepFunction He3 0.1 0.02 mm

#=====================================
# Hadronic processes
#=====================================

# Elastic scattering of all particles except low energy neutrons
/gate/physics/addProcess HadronElastic 
/gate/physics/processes/HadronElastic/setModel G4HadronElastic 
/gate/physics/processes/HadronElastic/G4HadronElastic/setEmin 0 MeV
/gate/physics/processes/HadronElastic/G4HadronElastic/setEmax 500 GeV

# Elastic scattering of low energy neutrons
/gate/physics/processes/HadronElastic/setModel G4NeutronHPElastic 
/gate/physics/processes/HadronElastic/G4NeutronHPElastic/setEmin 0 MeV
/gate/physics/processes/HadronElastic/G4NeutronHPElastic/setEmax 20 MeV
 
# Inelastic scattering for protons
/gate/physics/addProcess ProtonInelastic
/gate/physics/processes/ProtonInelastic/setModel G4BinaryCascade
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmin 0 MeV
/gate/physics/processes/ProtonInelastic/G4BinaryCascade/setEmax 500 GeV

# Inaelastic scattering for GenericIons, deuteron, trion, He3, alpha
/gate/physics/addProcess IonInelastic deuteron
/gate/physics/addProcess IonInelastic triton
/gate/physics/addProcess IonInelastic He3
/gate/physics/addProcess IonInelastic alpha
/gate/physics/addProcess IonInelastic GenericIon

/gate/physics/processes/IonInelastic/setModel G4QMDReaction deuteron
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV deuteron
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 500 GeV deuteron
/gate/physics/processes/IonInelastic/setModel G4QMDReaction triton
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV triton
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 500 GeV triton
/gate/physics/processes/IonInelastic/setModel G4QMDReaction He3
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV He3
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 500 GeV He3
/gate/physics/processes/IonInelastic/setModel G4QMDReaction alpha
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV alpha
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 500 GeV alpha
/gate/physics/processes/IonInelastic/setModel G4QMDReaction GenericIon
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmin 0 MeV GenericIon
/gate/physics/processes/IonInelastic/G4QMDReaction/setEmax 500 GeV GenericIon

# Inaelastic scattering for neutrons
/gate/physics/addProcess NeutronInelastic
# Fast
/gate/physics/processes/NeutronInelastic/setModel G4NeutronHPInelastic 
/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmin 0 MeV 
/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmax 20 MeV 
# Slow
/gate/physics/processes/NeutronInelastic/setModel G4BinaryCascade 
/gate/physics/processes/NeutronInelastic/G4BinaryCascade/setEmin 19 MeV 
/gate/physics/processes/NeutronInelastic/G4BinaryCascade/setEmax 500 GeV 

/gate/physics/addProcess PionPlusInelastic
/gate/physics/processes/PionPlusInelastic/setModel G4LEPionPlusInelastic

/gate/physics/addProcess PionMinusInelastic
/gate/physics/processes/PionMinusInelastic/setModel G4LEPionMinusInelastic

/gate/physics/addProcess NeutronCapture
/gate/physics/processes/NeutronCapture/setModel G4NeutronHPCapture
/gate/physics/processes/NeutronCapture/G4NeutronHPCapture/setEmin 0 MeV
/gate/physics/processes/NeutronCapture/G4NeutronHPCapture/setEmax 20 MeV
/gate/physics/processes/NeutronCapture/setModel G4LCapture
/gate/physics/processes/NeutronCapture/G4LCapture/setEmin 14 MeV
/gate/physics/processes/NeutronCapture/G4LCapture/setEmax 20 GeV
/gate/physics/processes/NeutronCapture/setDataSet G4NeutronHPCaptureData
/gate/physics/processes/NeutronCapture/setDataSet G4HadronCaptureDataSet

/gate/physics/addProcess Fission
/gate/physics/processes/Fission/setModel G4NeutronHPFission
/gate/physics/processes/Fission/G4NeutronHPFission/setEmin 0 MeV
/gate/physics/processes/Fission/G4NeutronHPFission/setEmax 20 MeV
/gate/physics/processes/Fission/setModel G4LFission
/gate/physics/processes/Fission/G4LFission/setEmin 14 MeV
/gate/physics/processes/Fission/G4LFission/setEmax 20 GeV
/gate/physics/processes/Fission/setDataSet G4NeutronHPFissionData
/gate/physics/processes/Fission/setDataSet G4HadronFissionDataSet

#/gate/physics/addProcess NeutronInelastic
#/gate/physics/processes/NeutronInelastic/setModel G4NeutronHPInelastic
#/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmin 0 MeV
#/gate/physics/processes/NeutronInelastic/G4NeutronHPInelastic/setEmax 20 MeV
#/gate/physics/processes/NeutronInelastic/setDataSet G4NeutronHPInelasticData neutron
#/gate/physics/processes/NeutronInelastic/setModel G4BinaryCascade
#/gate/physics/processes/NeutronInelastic/G4BinaryCascade/setEmin 14 MeV
#/gate/physics/processes/NeutronInelastic/G4BinaryCascade/setEmax 20 GeV
#/gate/physics/processes/NeutronInelastic/setDataSet G4NeutronInelasticCrossSection neutron

/gate/physics/addProcess Decay
/gate/physics/addProcess RadioactiveDecay

#=====================================
# Options
#=====================================
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 TeV
/gate/physics/setDEDXBinning 220
/gate/physics/setLambdaBinning 220
#/gate/physics/Gamma/SetCutInRegion world 0.1 mm
#/gate/physics/Electron/SetCutInRegion world 0.1 mm
#/gate/physics/Positron/SetCutInRegion world 0.1 mm
#/gate/physics/Proton/SetCutInRegion world 0.1 mm






