/gate/physics/addPhysicsList QGSP_BERT_HP_EMY

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/Positron/SetCutInRegion world 1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm

/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm


/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter e-

/gate/physics/addProcess Decay
/gate/physics/addProcess RadioactiveDecay

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#/gate/physics/displayCuts
/gate/physics/print output/physics.txt